(ns ciwi.operator
  (:refer-clojure :exclude [concat name repeat])
  (:require [ciwi.operator.core :as core]
            [ciwi.operator.primitives :as primitives]))

(def operator core/operator)
(def operator? core/operator?)
(def apply-op core/apply-op)
(def invert-op core/invert-op)

(def repeated-motif primitives/repeated-motif)
(def partition-by-frequency primitives/partition-by-frequency)

(def add primitives/add)
(def sub primitives/sub)
(def mult primitives/mult)
(def dot primitives/dot)
(def negate primitives/negate)
(def lessthan primitives/lessthan)
(def equal primitives/equal)
(def logical-not primitives/logical-not)
(def logical-and primitives/logical-and)
(def logical-or primitives/logical-or)
(def len primitives/len)
(def brange primitives/brange)
(def trange primitives/trange)
(def mean primitives/mean)
(def repeat primitives/repeat)
(def map-op primitives/map-op)
(def cumsum primitives/cumsum)
(def insert primitives/insert)
(def concat primitives/concat)
(def getitem primitives/getitem)
(def setitem primitives/setitem)

(def registry primitives/registry)
