(ns ciwi.dense.protocols)

(defprotocol DenseArray
  (-backend [x])
  (-dtype [x])
  (-shape [x])
  (-ndim [x])
  (-size [x])
  (-ravel [x])
  (-tolist [x])
  (-array-info [x])
  (-content-fingerprint [x])
  (-same-content? [x y]))

(defprotocol DenseBackend
  (-backend-id [backend])
  (-array [backend data opts])
  (-from-flat [backend flat shape opts])
  (-array-like [backend template flat opts])
  (-arange [backend start stop step opts])
  (-tile [backend n motif opts])
  (-concatenate [backend xs opts])
  (-elementwise [backend f xs opts])
  (-dot [backend x y])
  (-sum [backend x axis])
  (-take-indices [backend x indices opts])
  (-put [backend x indices values opts])
  (-cumsum [backend x opts])
  (-diff [backend x opts]))
